env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-hooks
  - prettier
rules:
  import/extensions: 0
  react/react-in-jsx-scope: 0
  react/prop-types: 0
  react/jsx-filename-extension: [1, { 'extensions': ['.js', '.jsx'] }]
  react/function-component-definition: 0
